export const SET_USER = 'SET_USER'
export const SET_CHANNEL = 'SET_CHANNEL'

export const SET_FAVOURITE_CHANNEL = 'SET_FAVOURITE_CHANNEL'
export const REMOVE_FAVOURITE_CHANNEL = 'REMOVE_FAVOURITE_CHANNEL'
